// AUTO-GENERATED by scripts/generate-plugins.js — do not edit by hand.
// To add a new component plugin, create a folder in
// component-plugins with its plugin.meta.ts and component, then re-run
// `npm start` / `npm run build:prod`.
import { IComponentPlugin } from './component-plugin.interface';
import { DashboardMenuSdaComponent } from './dashboard-menu-sda/dashboard-menu.component';

export const COMPONENT_PLUGINS: IComponentPlugin[] = [
    {
        type: 'report-toolbar',
        label: 'Menú del informe',
        i18n: 'dashboardMenuLabel',
        menuIcon: 'pi-bars',
        permissions: ['edit'],
        component: DashboardMenuSdaComponent,
    },
];
