'use strict';

module.exports = {
    requiredFields: ['type', 'label', 'componentFile', 'componentExport'],

    buildOutput(plugins) {
        const imports = plugins
            .map((p) => `import { ${p.componentExport} } from './${p.dir}/${p.componentFile.replace(/^\.\//, '')}';`)
            .join('\n');

        const entries = plugins
            .map(
                (p) => [
                    `    {`,
                    `        type: '${p.type}',`,
                    `        label: '${p.label}',`,
                    `        i18n: '${p.i18n || ''}',`,
                    `        menuIcon: '${p.menuIcon || ''}',`,
                    `        permissions: [${(p.permissions || []).map((x) => `'${x}'`).join(', ')}],`,
                    `        component: ${p.componentExport},`,
                    `    },`,
                ].join('\n')
            )
            .join('\n');

        return `// AUTO-GENERATED by scripts/generate-plugins.js — do not edit by hand.
// To add a new component plugin, create a folder in
// component-plugins with its plugin.meta.ts and component, then re-run
// \`npm start\` / \`npm run build:prod\`.
import { IComponentPlugin } from './component-plugin.interface';
${imports}

export const COMPONENT_PLUGINS: IComponentPlugin[] = [
${entries}
];
`;
    },
};